"use client";

import { useState } from "react";
import type { CSSProperties, FormEvent } from "react";

function SplitText({ children }: { children: string }) {
  const words = children.split(" ");
  let index = 0;
  return (
    <span className="split-text" aria-label={children}>
      {words.map((word, wordIndex) => {
        const characters = Array.from(word).map((character) => ({ character, index: index++ }));
        return <span className="split-word" aria-hidden="true" key={`${word}-${wordIndex}`}>{characters.map(({ character, index: charIndex }) => <span className="split-char" key={`${character}-${charIndex}`} style={{ "--char-index": charIndex } as CSSProperties}>{character}</span>)}</span>;
      })}
    </span>
  );
}

export default function SiteExperience() {
  const [status, setStatus] = useState("");
  const [hasError, setHasError] = useState(false);
  function onSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const name = String(data.get("name") || "").trim();
    const email = String(data.get("email") || "").trim();
    const project = String(data.get("project") || "").trim();
    if (!name || !email || !project || !/^\S+@\S+\.\S+$/.test(email)) { setHasError(true); setStatus("Please complete the required fields and check your email address."); return; }
    setHasError(false); setStatus("Thank you. Your enquiry has been prepared for the NEXMOD team."); event.currentTarget.reset();
  }
  function onHeroPointerMove(event: React.PointerEvent<HTMLElement>) {
    const rect = event.currentTarget.getBoundingClientRect();
    event.currentTarget.style.setProperty("--pointer-x", ((event.clientX - rect.left) / rect.width - .5).toFixed(3));
    event.currentTarget.style.setProperty("--pointer-y", ((event.clientY - rect.top) / rect.height - .5).toFixed(3));
  }
  return <main id="top">
    <a className="skip-link" href="#content">Skip to content</a>
    <header className="site-header"><a className="brand-logo" href="#top" aria-label="NEXMOD home"><img src="/assets/nexmod-logo.png" alt="NEXMOD Modular Buildings" /></a><nav className="main-nav" aria-label="Primary navigation"><a href="#about">About</a><a href="#buildings">Modular Buildings</a><a href="#capabilities">Capabilities</a><a href="#projects">Projects</a><a href="#innovation">Innovation</a></nav><a className="nav-contact" href="#contact">Contact</a></header>
    <div id="content">
      <section className="hero" aria-labelledby="hero-title" onPointerMove={onHeroPointerMove}><div className="hero-media"><img src="/assets/hero-modular-building.png" alt="" /></div><div className="hero-scrim" /><div className="hero-content"><p className="eyebrow">NEXMOD / Australia</p><h1 id="hero-title"><SplitText>Smarter modular buildings for Australia.</SplitText></h1><p className="hero-copy">Integrated design, engineering, manufacturing and delivery for building outcomes that need to work in the real world.</p><div className="hero-actions"><a className="button button-primary" href="#contact">Discuss your project</a><a className="text-link" href="#buildings">Explore modular buildings</a></div></div></section>
      <section id="about" className="intro section-grid reveal" aria-labelledby="about-title"><div className="intro-lead"><p className="eyebrow">A complete building approach</p><h2 id="about-title"><SplitText>Designed as a system. Delivered for the real world.</SplitText></h2></div><div className="intro-copy"><p>Building projects involve complex sites, competing priorities and many stakeholders. NEXMOD brings modular design, engineering, manufacturing and project delivery into one coordinated pathway.</p><p>We help project teams make important decisions earlier, resolve interfaces with greater clarity and stay focused on the quality of the finished building.</p><a className="text-link" href="#capabilities">See our capabilities</a></div></section>
      <section id="buildings" className="stack-wrap" aria-labelledby="buildings-title"><article className="stack-card stack-card-one"><img src="/assets/interior-learning-space.png" alt="A completed contemporary Australian learning space with timber, blue-green acoustic surfaces and expansive windows." /><div className="stack-content"><p className="eyebrow">Modular buildings</p><h2 id="buildings-title"><SplitText>Whole spaces, not a collection of parts.</SplitText></h2><p>NEXMOD develops room-scale modular building systems for commercial, education, healthcare, accommodation and industrial projects.</p></div></article><article className="stack-card stack-card-two"><img src="/assets/manufacturing-module.png" alt="A precise room-scale building module being completed in a controlled manufacturing environment." /><div className="stack-content"><p className="eyebrow">Capability</p><h2><SplitText>Coordination starts before site work does.</SplitText></h2><p>Design intent, engineering requirements and manufacturing considerations are developed together, so the building can move forward with fewer unresolved interfaces.</p></div></article><article className="stack-card stack-card-three"><img src="/assets/regional-project.png" alt="A refined modular building set within an Australian regional landscape." /><div className="stack-content"><p className="eyebrow">Australian context</p><h2><SplitText>A solution shaped for the project in front of you.</SplitText></h2><p>Every project responds to its own location, people, approvals and delivery requirements. Our approach begins with that reality.</p></div></article></section>
      <section id="capabilities" className="capabilities" aria-labelledby="capabilities-title"><div className="section-heading reveal"><p className="eyebrow">Integrated delivery</p><h2 id="capabilities-title"><SplitText>One joined-up modular delivery partner.</SplitText></h2><p>Our capability connects the work that determines whether modular delivery succeeds.</p></div><div className="capability-grid"><article className="capability reveal"><span>01</span><h3>Modular design</h3><p>Building concepts shaped around repeatable, buildable and user-focused modular principles.</p></article><article className="capability reveal"><span>02</span><h3>Engineering</h3><p>Technical thinking that works alongside the modular design and the requirements of the wider project team.</p></article><article className="capability reveal"><span>03</span><h3>Manufacturing</h3><p>Manufacturing insight brought in early, when it can improve coordination and buildability.</p></article><article className="capability reveal"><span>04</span><h3>Project delivery</h3><p>Off-site and on-site activity connected around a clear, practical building outcome.</p></article></div></section>
      <section id="projects" className="project-feature" aria-labelledby="projects-title"><div className="project-image reveal"><img src="/assets/regional-project.png" alt="Completed low-rise modular building among native Australian planting." /></div><div className="project-copy reveal"><p className="eyebrow">Projects</p><h2 id="projects-title"><SplitText>Project stories should make the outcome clear.</SplitText></h2><p>Every NEXMOD project begins with a different brief. The work is to understand what the building needs to achieve and coordinate a pathway that supports it.</p><p className="project-note">Approved project case studies will appear here once project names, imagery and client references are cleared for public release.</p><a className="text-link" href="#contact">Talk about your project</a></div></section>
      <section id="innovation" className="innovation" aria-labelledby="innovation-title"><div className="innovation-copy reveal"><p className="eyebrow">Innovation</p><h2 id="innovation-title"><SplitText>Better building decisions start early.</SplitText></h2><p>Innovation at NEXMOD is practical. It is the work of bringing the right people, information and decisions together early enough to improve the way a building is designed and delivered.</p><a className="button button-secondary" href="#contact">Start a conversation</a></div><div className="innovation-media"><img src="/assets/manufacturing-module.png" alt="" /></div></section>
      <section id="news" className="news" aria-labelledby="news-title"><div className="section-heading reveal"><p className="eyebrow">News</p><h2 id="news-title"><SplitText>Clear thinking for better building decisions.</SplitText></h2><p>Project updates, practical insights and news from across design, engineering, manufacturing and delivery.</p></div><div className="news-layout"><article className="news-lead reveal"><p>Latest update</p><h3>News and project insights are coming soon.</h3><a className="text-link" href="#contact">Subscribe for updates</a></article><div className="news-notes reveal"><p>Company news</p><p>Project updates</p><p>Design and engineering insight</p></div></div></section>
      <section id="contact" className="contact" aria-labelledby="contact-title"><div className="contact-copy reveal"><p className="eyebrow">Contact</p><h2 id="contact-title"><SplitText>Let's talk about your project.</SplitText></h2><p>Whether you are exploring an early idea or progressing an active project, NEXMOD can help you start the right conversation about a modular building approach.</p><p className="contact-detail">[Office address, Australia]<br />[Email address]<br />[Australian phone number]</p></div><form className="contact-form reveal" noValidate onSubmit={onSubmit}><div className={`field ${hasError ? "is-error" : ""}`}><label htmlFor="name">Name</label><input id="name" name="name" autoComplete="name" required /></div><div className="field"><label htmlFor="organisation">Organisation</label><input id="organisation" name="organisation" autoComplete="organization" /></div><div className={`field ${hasError ? "is-error" : ""}`}><label htmlFor="email">Email</label><input id="email" name="email" type="email" autoComplete="email" required /></div><div className={`field ${hasError ? "is-error" : ""}`}><label htmlFor="project">Tell us about your project</label><textarea id="project" name="project" rows={4} required /></div><p className={`form-status ${hasError ? "is-error" : status ? "is-success" : ""}`} aria-live="polite">{status}</p><button className="button button-primary" type="submit">Send enquiry</button><p className="privacy">By submitting this form, you agree that NEXMOD may use your details to respond to your enquiry in accordance with our Privacy Policy.</p></form></section>
    </div>
    <footer className="site-footer"><a className="brand-logo footer-logo" href="#top"><img src="/assets/nexmod-logo.png" alt="NEXMOD Modular Buildings" /></a><p>Integrated modular building solutions for Australian projects.</p><a className="text-link" href="#contact">Contact NEXMOD</a></footer>
  </main>;
}
